modLoader = "javafml"
loaderVersion = "[35,)"
#issueTrackerURL = ""
license = "LGPL v2.1"

[[mods]]
modId = "multis"
version = "${version}"
displayName = "Multis Mod"
authors = "Blancworks"
description = '''
A mod that allows runtime creation/destruction of items.
'''
#logoFile = ""

[[dependencies.examplemod]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"